### ISSUE TITLE
Hide the infobox entirley

### ISSUE THREAD

**Issue by ymeros** [InfernoStats/Brewing#9]
Would it possible to have an option to hide the infoboxes on the screen entirely regardless of ale status? I find that showing the status as a chat message is enough for me to know. If so, could a chat message also be sent if an ale has gone bad? Unless this is already an option which I can't find.

**Comment by dorrzun** [comment]
@ymeros I'm not a developer for this plugin, however there _is_ existing support for bad ale!
I might make a PR in the future...

**Comment by InfernoStats** [comment]
Set "Display Vats" or "Display Barrels" to "NONE" when the next version of the plugin is available.
